# Generated by Django 5.2.13 on 2026-05-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='FoodOrder',
        ),
    ]
